apiVersion: v1
kind: Namespace
metadata:
  name: erp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: erp
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: postgres
          image: postgres
        - name: odoo-server
          image: odoo
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-map
                  key: USER_NAME
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-map
                  key: PASSWORD
          ports:
            - containerPort: 8069
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: erp
  labels:
    app: odoo
spec:
  type: NodePort
  ports:
    - targetPort: 8069
      port: 8069
      nodePort: 30002
  selector:
    app: odoo